### ISSUE TITLE
Ability to click submenus

### ISSUE THREAD

**Issue by zyuhel** [swisnl/jQuery-contextMenu#483] opened 2016-12-08 09:21 UTC
occasionally It is a useful ability to click on items containing submenus. For example if menu is used for tree categories selector. 
I have made a Pull request #481 adding option for this.

**Comment by bbrala** [comment] 2016-12-09 15:14
Thanks! Merged the branch.

**Closed by bbrala** 2016-12-09 15:14 UTC

**Comment by CipherTrustee** [comment] 2019-12-04 05:35
There may be a regression on this feature...it fails because the key for an item that is a submenu is unknown at the time of a click event:

// abort if the key is unknown or disabled or is a menu
```
 if (!opt.items[key] || $this.is('.' + root.classNames.disabled + ', .context-menu-separator, .' + root.classNames.notSelectable) || ($this.is('.context-menu-submenu') && root.selectableSubMenu === false )) {
                    return;
}
```
