### ISSUE TITLE
Separator or plain text button fails on subMenu

### ISSUE THREAD

**Issue by tlemmons** [swisnl/jQuery-contextMenu#279] opened 2015-09-22 22:37 UTC
I am trying to put a save on the bottom of a set of checkboxes like so:
           $.contextMenu({
                // define which elements trigger this menu
                selector: ".imageBlock",
                callback: function (key, options) {
                    var m = "clicked: " + key;
                    window.console && console.log(m) || alert(m);
                },
                items: {
                    "Folders": {
                        "name": "Folders",
                        "items": {
                            "folder-1": { name: "folder-1", type: 'checkbox', selected: false },
                            "folder-2": { name: "folder-2", type: 'checkbox', selected: true },
                            "folder-3": { name: "folder-3", type: 'checkbox', selected: false },
                            "savef": { name: "save"},
                        }
                    },
                    "Collections": {
                        "name": "Collections",
                        "items": {
                            "Collection-1": { name: "Collection-1", type: 'checkbox', selected: true },
                            "Collection-2": { name: "Collection-2", type: 'checkbox', selected: false },
                            "Collection-3": { name: "Collection-3", type: 'checkbox', selected: true },
                            "savec": { name: "save"},
                        }
                    },

                }
            });

When I run this though I get an error from Chrome 

.Uncaught TypeError: Cannot read property 'icon' of undefined @ jquery.contextMenu.js:1165 
I walked thought the code but could not tell what was wrong. Any help appreciated.  
If I remove the two save items it works fine.

edit:
I got the save to work - not sure what changed but the problem was actually trying to put a seperator  before the save like:

                            sep1:"------------------",
                            savef: { name: "Save" },

**Comment by bbrala** [comment] 2015-09-23 07:27
Weird, i'll have a look soon. THanks for the report.

**Comment by bbrala** [comment] 2015-09-23 12:19
I've put this in a demo and cannot reproduce the problem in the master branch. A new version will be released soon which should fix your problems then.

On a side-note, you should not add a , (comma) behind the last row of an object definition. This will not work in all browsers.

                    "savef": { name: "save"},
should be:

                    "savef": { name: "save"}


Your original pasted code:

    $.contextMenu({
        // define which elements trigger this menu
        selector: ".imageBlock",
        callback: function (key, options) {
            var m = "clicked: " + key;
            window.console && console.log(m) || alert(m);
        },
        items: {
            "Folders": {
                "name": "Folders",
                "items": {
                    "folder-1": { name: "folder-1", type: 'checkbox', selected: false },
                    "folder-2": { name: "folder-2", type: 'checkbox', selected: true },
                    "folder-3": { name: "folder-3", type: 'checkbox', selected: false },
                    "savef": { name: "save"},
                }
            },
            "Collections": {
                "name": "Collections",
                "items": {
                    "Collection-1": { name: "Collection-1", type: 'checkbox', selected: true },
                    "Collection-2": { name: "Collection-2", type: 'checkbox', selected: false },
                    "Collection-3": { name: "Collection-3", type: 'checkbox', selected: true },
                    "savec": { name: "save"},
                }
            },

        }
    });

**Closed by bbrala** 2015-09-23 12:19 UTC
