### ISSUE TITLE
Troubles with Font Awesome Icons

### ISSUE THREAD

**Issue by Slowchaos** [swisnl/jQuery-contextMenu#408] opened 2016-06-14 13:47 UTC
If I use two font awesome icons in a row, such as:

`items: {
                                        "new": {name: "New", icon: "fa-clone"},
                                        "edit": {name: "Edit", icon: "fa-edit"},
                                        "copy": {name: "Copy", icon: "copy"},
                                        "paste": {name: "Paste", icon: "paste"},
                                        "delete": {name: "Delete", icon: "delete"},
                                        "sep1": "---------",
                                        "quit": {name: "Quit", icon: "quit"}
                                    }`

... the second font awesome Item will appear horizontally to the right of the previous font awesome item in the menu. However, if I do not use font awesome icons next to each other, everything is fine. If I use all font awesome icons I end up with a horizontal menu instead of a vertical menu.

I am using the latest download of this context menu and jquery 1.11.1 and FontAwesome 4.6.3. Have tried a couple of different versions of font awesome to no avail.

**Comment by bbrala** [comment] 2016-06-14 17:20
Hmm, that sounds like a bug in the CSS, will have a look soon.

**Comment by HefloRicardo** [comment] 2016-06-15 00:35
I do have a workaround here:
try to use the icon as a function and create a new structure for your menu items:
`                
icon: function (opt, $itemEl) {
    $itemEl.children("span").html("<i class='fa fa-edit'></i><span>Edit</span>");
    return null;
}
`

And with this new structure, you will have to apply some CSS to make it looks great again.

`.context-menu-item {
    padding-left: 10px;
}
.context-menu-item i {
    padding-right: 10px;
}`

**Comment by bbrala** [comment] 2016-06-15 08:01
Hopefully we dont need to change the structure like that. :)

**Comment by HefloRicardo** [comment] 2016-06-15 23:07
Yes, i know and i'm also looking forward this bug fix.
Just commenting a possible workaround for other users who also use font-awesome fonts in the meanwhile.

**Comment by bbrala** [comment] 2016-06-17 13:45
When i try this on an empty html page, i see no problem...

I tested this in the root of the repos: https://gist.github.com/bbrala/4743aa7b0d2bb89d74c0a617b366fb81

**Comment by bbrala** [comment] 2016-07-17 15:10
Since i can't reproduce this and there is no furthere response I will be closing this issue.

**Closed by bbrala** 2016-07-17 15:10 UTC
Labels: Bug, Waiting for response
