### ISSUE TITLE
Focus not set on element when right click

### ISSUE THREAD

**Issue by dbarrett84** [swisnl/jQuery-contextMenu#482] opened 2016-12-07 12:56 UTC
I have added the context menu on a `table` element within a `contenteditable` area.

When I right click it shows the correct context menu, **BUT** the selected element is not updated because the right click has stopped propagation and therefore my options in the menu are being applied to the wrong element.

See for example:
https://jsfiddle.net/dbarrett84/s4j64Lo7/1/

Right click in the column heading and then in caption, cursor doesn't move to the caption it stays in the column heading cell.

**Comment by bbrala** [comment] 2016-12-09 15:23
Hmm, i see what you mean. Seems the problem is propably [this code](https://github.com/swisnl/jQuery-contextMenu/blob/master/src/jquery.contextMenu.js#L453-L457). It doesn't really click, but finds the target based on the position.

I might be able to do that differently so it wont stop there without breaking the code. I'll try and have a look soon.

**Comment by robfenlon** [comment] 2016-12-12 15:47
Hi, I have a PR up that will fix this issue for contenteditable elements:
#486 
Thanks!

**Comment by bbrala** [comment] 2016-12-12 16:14
Thanks for making PR available for this. @dbarrett84 think you can have a look if that PR fixes it for you?

**Comment by dbarrett84** [comment] 2016-12-12 16:23
Ya looks good, fixes my issue.

**Comment by bbrala** [comment] 2016-12-15 20:27
Merged your PR, thanks!

**Closed by bbrala** 2016-12-15 20:27 UTC
Labels: Bug

**Comment by dbarrett84** [comment] 2016-12-16 08:47
Excellent, thanks very much Björn and Rob!
